# Copyright 2021 The Karavel Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Build
        run: make build
      - name: Run tests
        run: make test
  container-image:
    if: github.ref == 'refs/heads/main'
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/karavel/cli
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=Karavel CLI
            org.opencontainers.image.description=The Karavel CLI
            org.opencontainers.image.vendor=The Karavel Project
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  binary:
    if: github.ref == 'refs/heads/main'
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload linux_386 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-linux_386
          path: dist/karavel_linux_386/*
      - name: Upload linux_amd64 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-linux_amd64
          path: dist/karavel_linux_amd64/*
      - name: Upload linux_arm64 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-linux_arm64
          path: dist/karavel_linux_arm64/*
      - name: Upload windows_386 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-windows_386
          path: dist/karavel_windows_386/*
      - name: Upload windows_amd64 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-windows_amd64
          path: dist/karavel_windows_amd64/*
      - name: Upload darwin_amd64 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-darwin_amd64
          path: dist/karavel_darwin_amd64/*
      - name: Upload darwin_arm64 build
        uses: "actions/upload-artifact@v2"
        with:
          name: karavel-cli-darwin_arm64
          path: dist/karavel_darwin_arm64/*
