name: Release Components
on:
  workflow_run:
    workflows: [ "Lint and Test" ]
    branches: [ main ]
    types:
      - completed

jobs:
  release-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/karavel/cli:edge
